CREATE TABLE users (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name  VARCHAR(255) NOT NULL,
  email      VARCHAR(255) NOT NULL UNIQUE,
  user_image VARCHAR(255),
  cpf        CHAR(11) UNIQUE CHECK (cpf ~ '^[0-9]{11}$'),
  password   TEXT NOT NULL
);
